In [262]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Building an item of features

The problem requires me to create a array for 4 users and their ratings as features, $X_1$ and $X_2$ as further features to indicate the type of movie. $X_1$ being a romantic movie and $X_2$ being the action type

In [263]:
a=np.array([[5,5,0,0,0.9,0],
          [5,np.nan,np.nan,0,1.0,0],
          [np.nan,4,0,np.nan,0.99,0],
          [0,0,5,4,0.1,1],
          [0,0,5,np.nan,0,0.9]])
a.shape

(5, 6)

In [264]:
names=["Alice","Bob","Carol","Dave","$x_1$","$x_2$"]
index=["Love at Last","Romance Forever","Cute Puppies","Non-stop","Swords and Karate"]

In [265]:
df=pd.DataFrame(a,columns=names, index=index) #creating a data frame with column names and index names

In [266]:
df.index.rename('Movies',inplace=True) #renaming the index

In [267]:
df

Alice  Bob  Carol  Dave  $x_1$  $x_2$
Movies                                                  
Love at Last         5.0  5.0    0.0   0.0   0.90    0.0
Romance Forever      5.0  NaN    NaN   0.0   1.00    0.0
Cute Puppies         NaN  4.0    0.0   NaN   0.99    0.0
Non-stop             0.0  0.0    5.0   4.0   0.10    1.0
Swords and Karate    0.0  0.0    5.0   NaN   0.00    0.9

In [268]:
df.iloc[2,:4] #exploring my data in my own way

Alice    NaN
Bob      4.0
Carol    0.0
Dave     NaN
Name: Cute Puppies, dtype: float64

# Lets check the user ratings for each person given the type of movie
Each movie rating and their set will be represent with the array $y_{ij}$ but in this case I am checking if the movie has been rated first before looking at the ratings. The array will be represented by r and if rated will be 1 and if not will be zero.

In [269]:
np.isnan(df) #searching for nan values

Alice    Bob  Carol   Dave  $x_1$  $x_2$
Movies                                                     
Love at Last       False  False  False  False  False  False
Romance Forever    False   True   True  False  False  False
Cute Puppies        True  False  False   True  False  False
Non-stop           False  False  False  False  False  False
Swords and Karate  False  False  False   True  False  False

# Now I will check the rating each user gave to a movie 

In [287]:
y=[]
y.append(np.array(df.iloc[:,:3]))

In [288]:
y=np.array(y)
y

array([[[ 5.,  5.,  0.],
        [ 5., nan, nan],
        [nan,  4.,  0.],
        [ 0.,  0.,  5.],
        [ 0.,  0.,  5.]]])

In [289]:
ratings=[]
for i in range(y.shape[0]):
    ratings.append(y[i][~np.isnan(y[i])])


In [293]:
y.shape

(1, 5, 3)

In [322]:
y# calling out y to see the array before I carry the next steps

array([[[ 5.,  5.,  0.],
        [ 5., nan, nan],
        [nan,  4.,  0.],
        [ 0.,  0.,  5.],
        [ 0.,  0.,  5.]]])

In [307]:
y[0:,0,0]

array([5.])

In [323]:
np.dot(x[0].reshape(-1,1),y[0:,0,0]) # using the reshape and dot product to create a di=ot product between a matrix and an
#array

array([4.5, 0. ])

In [320]:
x.shape

(5, 2)

# Dealing with the predictions 

In [291]:
a.shape

(5, 6)

In [292]:
y1

Movies
Love at Last         5.0
Romance Forever      5.0
Cute Puppies         NaN
Non-stop             0.0
Swords and Karate    0.0
Name: Alice, dtype: float64

In [276]:
predict_alice=[]

x=np.array([[0.9 , 0.  ],
       [1.  , 0.  ],
       [0.99, 0.  ],
       [0.1 , 1.  ],
       [0.  , 0.9 ]])
x.shape

(5, 2)

# Testing the Predictions with Alice as $y_1$

In [277]:
np.dot(y1[0],x[0])

array([4.5, 0. ])

In [278]:
np.dot(y1[1],x[1])+0

array([5., 0.])

In [279]:
y1.iloc[0]

5.0

# Now it is time for Automation. And error calculation
# Will be back